[project]
name = "sacca"
version = "0.1.0"
description = "Speedcubing Algorithm Complexity Coefficient Analyzer"
readme = "README.md"
license = "BSL-1.0"
license-files = ["LICEN[SC]E*"]
keywords = ["speedcubing", "cubing", "ml"]
requires-python = ">=3.11"


authors = [
    {name = "discocat", email = "me@runderscore.com"},
]

dependencies = [
    "pandas>=2.3"
]

[project.urls]
Homepage = "https://sacca.runderscore.com"
Documentation = "https://sacca.runderscore.com/docs"
Repository = "https://github.com/d1scocat/sacca"

[project.optional-dependencies]
dev = [
    "ruff",
]

cli = [
    "rich",
    "typer"
]

[project.scripts]
lint = "sacca.scripts.lint:main"

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I", "B"]
lint.ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/*" = ["S101"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]